const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const state={view:'home',fuel:62,reserve:20,critical:8,speed:0,engine:91,outside:19,temp:22,fan:2,ac:true,recirc:false,roof:65,shade:35,volume:42,brightness:72};
function clock(){const d=new Date();$('#clock').textContent=d.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',hour12:false});} clock();setInterval(clock,15000);
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>e.classList.remove('show'),1700)}
function view(name){state.view=name;$$('.view').forEach(v=>v.classList.toggle('active',v.dataset.view===name));$$('.dock-btn').forEach(b=>b.classList.toggle('active',b.dataset.action===name));window.scrollTo(0,0)}
$$('[data-action]').forEach(b=>b.addEventListener('click',()=>view(b.dataset.action)));
function render(){
 $('#fuelValue').textContent=state.fuel;$('#fuelBar').style.width=state.fuel+'%';$('#fuelRing').style.strokeDashoffset=308-(308*state.fuel/100);$('#fuelState').textContent=state.fuel<=state.critical?'CRITICAL':state.fuel<=state.reserve?'RESERVE':'NORMAL';$('#fuelState').style.color=state.fuel<=state.reserve?'var(--red)':'var(--green)';$('#reserveLabel').textContent=state.reserve+'%';$('#range').textContent=Math.max(0,Math.round(state.fuel*6.78));$('#range2').textContent=Math.max(0,Math.round(state.fuel*6.78));
 $('#speed').textContent=state.speed;$('#diagSpeed').textContent=state.speed+' km/h';$('#rpm').textContent=Math.round(720+state.speed*26);$('#engineTemp').textContent=state.engine+'°C';$('#engineMini').textContent=state.engine+'°C';$('#outsideTemp').textContent=state.outside+'°';$('#simSpeedVal').textContent=state.speed;$('#simFuelVal').textContent=state.fuel+'%';$('#simEngineVal').textContent=state.engine+'°C';$('#simOutsideVal').textContent=state.outside+'°C';
 $('#climateTemp').textContent=state.temp;$('#driverTemp').textContent=state.temp+'°';$('#fanMini').textContent=state.fan;$('#acMini').textContent=state.ac?'ON':'OFF';$('#acPage').textContent=state.ac?'ON':'OFF';$('#sunroofMini').textContent=state.roof+'%';$('#sunroofQuick').textContent=state.roof+'%';$('#roofPercent').textContent=state.roof+'%';$('#diagRoof').textContent=state.roof+'%';$('#roofSlider').value=state.roof;$('#shadePercent').textContent=state.shade+'%';$('#volumeValue').textContent=state.volume+'%';$('#volumeSlider').value=state.volume;$('#brightnessValue').textContent=state.brightness+'%';$('#reserveValue').textContent=state.reserve+'%';$('#brightnessSlider').value=state.brightness;$('#reserveSlider').value=state.reserve;document.documentElement.style.setProperty('--brightness',state.brightness/100);
 $('#gear').textContent=state.speed===0?'P':'D';$('#driveStatus').textContent=state.speed===0?'P':'D';
}
$('#brightnessSlider').addEventListener('input',e=>{state.brightness=+e.target.value;render()});$('#volumeSlider').addEventListener('input',e=>{state.volume=+e.target.value;render()});$('#reserveSlider').addEventListener('input',e=>{state.reserve=+e.target.value;render();toast('Reserve warning set to '+state.reserve+'%')});
$$('[data-temp]').forEach(b=>b.addEventListener('click',()=>{state.temp=Math.min(30,Math.max(16,state.temp+(b.dataset.temp==='+'?1:-1)));render()}));
$$('#fanControls button').forEach((b,i)=>b.addEventListener('click',()=>{state.fan=i;$$('#fanControls button').forEach(x=>x.classList.remove('active'));b.classList.add('active');render()}));
function toggle(el,key){el.addEventListener('click',()=>{state[key]=!state[key];el.classList.toggle('on',state[key]);render()})} toggle($('#acToggle'),'ac');toggle($('#recircToggle'),'recirc');
$$('[data-air]').forEach(b=>b.addEventListener('click',()=>{$$('[data-air]').forEach(x=>x.classList.remove('active'));b.classList.add('active');toast('Airflow: '+b.dataset.air)}));
$('#roofSlider').addEventListener('input',e=>{state.roof=+e.target.value;render()});$$('[data-roof]').forEach(b=>b.addEventListener('click',()=>{state.roof=b.dataset.roof==='close'?0:b.dataset.roof==='vent'?20:100;render();toast('Sunroof '+b.dataset.roof)}));$$('[data-shade]').forEach(b=>b.addEventListener('click',()=>{state.shade=Math.min(100,Math.max(0,state.shade+(b.dataset.shade==='+'?5:-5)));render()}));
$$('.toggle').forEach(t=>{if(!t.id)t.addEventListener('click',()=>{t.classList.toggle('on')})});
[['simSpeed','speed'],['simFuel','fuel'],['simEngine','engine'],['simOutside','outside']].forEach(([id,key])=>$('#'+id).addEventListener('input',e=>{state[key]=+e.target.value;render()}));
$$('.theme-row button').forEach(b=>b.addEventListener('click',()=>{$$('.theme-row button').forEach(x=>x.classList.remove('active'));b.classList.add('active');toast('Theme: '+b.textContent)}));$$('.drive-modes button').forEach(b=>b.addEventListener('click',()=>{$$('.drive-modes button').forEach(x=>x.classList.remove('active'));b.classList.add('active');toast('Drive mode: '+b.textContent)}));
// Simple simulated live motion: only changes while user enables it through speed slider, no hidden background movement.
const boot=$('#boot'),start=$('#startBtn');start.addEventListener('click',()=>{start.disabled=true;$('.boot-bar i').style.width='100%';setTimeout(()=>boot.classList.add('hide'),1800)});setTimeout(()=>$('.boot-bar i').style.width='22%',120);render();
